# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

target <- function(x, pars) {
    .Call('demo_target', PACKAGE = 'demo', x, pars)
}

mcmcexample_rcpp <- function(x0, w, nsteps, pars) {
    .Call('demo_mcmcexample_rcpp', PACKAGE = 'demo', x0, w, nsteps, pars)
}

