// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/simplemcmc.h"
#include <Rcpp.h>

using namespace Rcpp;

// target
double target(const std::vector<double>& x, const std::vector<double>& pars);
RcppExport SEXP simplemcmc_target(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pars(parsSEXP);
    __result = Rcpp::wrap(target(x, pars));
    return __result;
END_RCPP
}
// mcmcexample_rcpp
Rcpp::List mcmcexample_rcpp(std::vector<double> x0, std::vector<double> w, int nsteps, std::vector<double> pars);
RcppExport SEXP simplemcmc_mcmcexample_rcpp(SEXP x0SEXP, SEXP wSEXP, SEXP nstepsSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type nsteps(nstepsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type pars(parsSEXP);
    __result = Rcpp::wrap(mcmcexample_rcpp(x0, w, nsteps, pars));
    return __result;
END_RCPP
}
